from smolagents import LiteLLMModel, CodeAgent

from tools import (
    predict_match,
    fetch_recent_form,
    fetch_head_to_head,
)

model = LiteLLMModel(
    model_id="ollama_chat/gemma3:4b",
    api_base="http://127.0.0.1:11434",
    num_ctx=8192,
)

agent = CodeAgent(
    tools=[
        predict_match,
        fetch_recent_form,
        fetch_head_to_head,
    ],
    model=model,
)

def predict_with_agent(team1: str, team2: str) -> dict:
    """
    Uses the LLM agent to orchestrate football prediction tools.

    Args:
        team1: Name of the first football team.
        team2: Name of the second football team.

    Returns:
        Structured prediction result generated by the prediction engine.
    """

    task = f"""
    You are an AI football analyst.

    Your task is to predict the match between "{team1}" and "{team2}".

    IMPORTANT RULES:

    1. You MUST call the tool:
       predict_match("{team1}", "{team2}")

    2. The predict_match tool is the source of truth.

    3. Do NOT calculate your own winner.

    4. Do NOT modify:
       - winner
       - confidence
       - team scores
       - weights
       - head-to-head data

    5. If additional context is needed, you may call:
       - fetch_recent_form("{team1}")
       - fetch_recent_form("{team2}")
       - fetch_head_to_head("{team1}", "{team2}")

    6. Return the exact dictionary returned by predict_match.

    Do not summarize.
    Do not convert it into natural language.
    Do not add extra fields.
    """

    result = agent.run(task)

    return result